development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:c377b6db6fef28f99751ada33d1cf7dd@sole.redistogo.com:10711/
  channel_prefix: message_production
